default:
  tags:
    - minerva-build

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"
  GIT_SUBMODULE_DEPTH: 1

build:
  stage: build
  image: dearpygui:latest
  script:
    - python3 -m venv venv
    - venv/bin/pip install setuptools wheel twine
    - venv/bin/python -m setup bdist_wheel --plat-name manylinux1_x86_64 --dist-dir dist
    - |
      DELETE_PATH=$(curl --silent --header "JOB-TOKEN: $CI_JOB_TOKEN" "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages?package_name=dearpygui" | jq ".[0]._links.delete_api_path")
      curl --request DELETE --header "JOB-TOKEN: $CI_JOB_TOKEN" ${DELETE_PATH//\"/}
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token venv/bin/python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
